### PR TITLE
fix actor schema: allow no nationality

### LINKED ISSUE #688: BULK_IMPORT_PATHS's instruction not clear. I cannot able to import
I got the following error:

`Z:\win>vault.exe`
`  vault:message Max. memory: 8136 MB +0ms`
`  vault:message Loading Z:\\win\\config.yaml... +0ms`
`  vault:message Registered plugins`
`  vault:message [] +0ms`
`  vault:message FFMPEG set to Z:\\win\\ffmpeg.exe +0ms`
`  vault:message FFPROBE set to Z:\\win\\ffprobe.exe +0ms`
`  vault:message Check https://github.com/boi123212321/porn-vault for discussion & updates +0ms`
`  vault:warn Creating backup in backups\\kcgu9nbk... +0ms`
`  vault:message Server running on Port 3000 +0ms`
`√ Making .db files compatible (if needed)`
`√ Compacted DB`
`√ Loading DB...`
`√ Integrity check done.`
`  vault:message Importing 1 new import files... +0ms`
`  vault:error Z:\\jsondata\\sample.json: could not read file. +0ms`
`  vault:error Cannot read property 'toUpperCase' of undefined +0ms`

my sample json look like this:

```
{
  "actors": {
    "123":     {
      "name":"Test",
      "bornOn":15125125125125
   }
  }
}

```
it was work in older version....
please give me a valid json example so that i can modiffy.

please add the "CustomField"  in the example

### PR DESCRIPTION
**Pull request by leadwolf**
- in the actor schema, `isValidCountryCode` would throw an error when the nationality was not defined, because it expected a string.
Since the nationality is not required in the db, the validator should allow an undefined code
Fixes #688

### CODE REVIEW

**Comment by leadwolf** [comment]
I didn't add tests for the schema because to me, it would be the same as testing the `validate` package, which is not the goal

**Comment by boi123212321** [comment]
Wouldn't that allow an empty ('') string as country code?

**Comment by leadwolf** [comment]
Do we need to make a distinction between the absence of the property, `null` and `""` ?

**Comment by boi123212321** [comment]
imo yes, `required` is set to false so i don't see why it doesn't work for undefined nationalities

**Comment by leadwolf** [comment]
It's because `isValidCountryCode` calls `getNationality ` on the tested code, but that does `str.toUpperCase` to check against the list of countries. So `undefined` or `null` will cause an TypeError, while an empty string will just fail validation.

**Pull request closed without merging**
