### PR TITLE
chore(readme): add docker instructions

### PR DESCRIPTION
**Pull request by Christopher-Caroni**
This PR adds instructions in the Readme on how to run the app with DOcker

### CODE REVIEW

**Comment by boi123212321** [comment]
Can you move the instructions into a separate .md file and reference it in the README?
That'd be perfect, the readme is getting a bit long

**Comment by Christopher-Caroni** [comment]
Sure. Is `docs/docker.md` alright ?

**Comment by boi123212321** [comment]
@Christopher-Caroni Sure

**Comment by porncloud** [comment]
The instructions should maybe suggest creating a "/backup" variable/path so that the backup files aren't stored inside the docker?

**Pull request merged**
