### PR TITLE
[Feature] add option to watch the library

### PR DESCRIPTION
**Pull request by Christopher-Caroni**
This PR adds an option to watch the library in addition to the existing way of walking the library folders.

If the `WATCH_LIBRARY` option is enabled, the video & image folders will be watched with chokidar.
Every `SCAN_INTERVAL`, the library will still be walked.

Importing is now done in a queue.
Video imports only start once all paths have been found.
Video processing only starts once all paths have been imported. It will also start automatically every time the import queue empties.
Image importing is done on the fly.

This might not be the most clean code, so don't worry about pointing out any problems or even code style

### CODE REVIEW

**Comment by boi123212321** [comment]
@Christopher-Caroni Could we somehow get unit/integration tests into this? I know it's not exactly trivial, but with the increasing complexity, it gets harder to keep track of what's going on

**Comment by Christopher-Caroni** [comment]
I guess the most relevant parts to test are the actual file detection, queue management and importing. I think the first two are mostly straightforward.
Then to test the importing process, we'd have to start the server, move around a few files and query the database to verify the result right ?

**Comment by boi123212321** [comment]
That would be the way to go I guess, yeah.
First try to get coverage on specific functions, then try to simulate it locally.

**Comment by Christopher-Caroni** [comment]
This PR can be rewritten for simpler functionality & testing. Will create a new one at a later time

**Pull request closed without merging**
