### PR TITLE
Add ability to use existing actor images as thumbnail, alt, hero

### PR DESCRIPTION
**Pull request by nevusmoonwriteup**
* Add the ability to set existing actor images as thumbnail, alt, hero
  * uses other random mdi icons that seemed to somewhat fit
  * example
image
* Fix lightbox in actor view by fetching additional graphql data for the lightbox component
* some Readme changes. The formatting is something that I can revert. Its not critical and mainly adjusts it to a linter that I'm used to
* The Readme change that **is** important is the information regarding the config file
  * the config file needs to exist in the predetermined location since run.sh expects it to exist
* Run.sh was creating the images folder using dynamic pathing instead of absolute pathing. It's been modified to match `/videos` to create the folder at root `/images/

### CODE REVIEW

**Comment by boi123212321** [comment]
I feel like the options need to be moved into a menu, because 4 buttons next to each other is starting to get a bit much

**Comment by nevusmoonwriteup** [comment]
It is probably too much. I was envisioning a hover and slide out from the corner so that it stays just 1 icon until you want to do something, but I'm not familiar enough with css to build that. I can look into it, I just don't know how long that'll take me

**Comment by nevusmoonwriteup** [comment]
@boi123212321 One big thing is I'm not sure if I'm using slot correctly. Let me know if its fine or not.

**Comment by nevusmoonwriteup** [comment]
Updated to do a scroll out effect on hover. I'm not able to get the css passed through to remove the padding. Any suggestion would be appreciated.

Screenshot 2020-05-16 22 09 47
Screenshot 2020-05-16 22 10 28

**Comment by Christopher-Caroni** [comment]
@nevusmoonwriteup You need to write `.image-speed-dial::v-deep .v-speed-dial__list` since the ActorDetails styles are scoped

**Comment by nevusmoonwriteup** [comment]
Done, also want to note that I did prettier format the ActorDetails.vue file. I tried to match the original formatting as close to possible, but it wasn't consistent so I just picked the least amount of changes. Let me know if there's a formatter/config I should be using.

**Comment by nevusmoonwriteup** [comment]
This should be ready to merge. Let me know what changes you'd like to be able to get this merged.

**Comment by nevusmoonwriteup** [comment]
Actually, I have no idea what's wrong with my git metadata. I'm going to delete my fork and recreate this.

**Pull request closed without merging**
